stages:
  - build
  - upload

build_server:
  image: gradle:9.4-jdk25
  stage: build
  artifacts:
    untracked: false
    expire_in: 7 days
    paths:
      - server.jar
  script:
    - git config --global user.email "ci@gitlab.eps-dev.de"
    - git config --global user.name "CI"
    - export BUILD_NUMBER=$CI_PIPELINE_IID
    - gradle applyAllPatches
    # I feel like these copies should be done automatically by gradle, but for some reason they aren't, so here we are
    - cp paper-api/src/generated/java paper-api/src/main -r
    - cp paper-server/src/generated/java paper-server/src/main -r
    - gradle build
    - cp kitty-server/build/libs/kitty-paperclip-26.1.2.local-SNAPSHOT.jar server.jar
  needs: []

upload:
  image:
    name: registry.cdev.nexus/kittysuite/version:main
    pull_policy: always
  stage: upload
  only:
    - main
  needs:
      - build_server
  script:
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.eps-dev.de/Lilly/kittypaperversions.git
    - python3 /app/generate.py
    - cd kittypaperversions
    - git config --global user.email "ci@gitlab.eps-dev.de"
    - git config --global user.name "CI"
    - git remote add gitlab_origin https://oauth:${token}@gitlab.eps-dev.de/Lilly/kittypaperversions.git
    - git add .
    - git commit -m "Update versions for build $CI_PIPELINE_IID"
    - git push gitlab_origin HEAD:main
